apiVersion: apps/v1
kind: Deployment
metadata:
  name: project005
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project005
  template:
    metadata:
      labels:
        app: project005
    spec:
      containers:
        - name: project005
          image: sidartasilva/project005:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5701
          - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: project005
spec:
  type: LoadBalancer
  selector:
    app: project005
  ports:
  - name: hazelcast
    port: 5701
  - name: app
    port: 8082